name: Daily ESP32 Connection Summary

on:
  workflow_call:
    secrets:
      MONGODB_TEST_OUTPUT_URI:
        required: true
  schedule:
    - cron:  '30 23 * * *'

env:
  MONGODB_TEST_OUTPUT_URI: ${{ secrets.MONGODB_TEST_OUTPUT_URI }}

jobs:
  canary:
    runs-on: "ubuntu-latest"
    defaults: 
      run:
        working-directory: ./canary
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Run Canary
        run: |
          python -m pip install -r requirements.txt
          python daily_summary.py
