name: Upload artifact to GCP Bucket

on:
  workflow_call:
    inputs:
      artifact-name:
        required: true
        type: string
      dir-name:
        required: true
        type: string

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
          path: ./downloaded-artifacts

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Upload to GCP
        run: |
          gsutil cp ./downloaded-artifacts/* gs://${{ secrets.GCP_BUCKET_NAME }}/${{ inputs.dir-name }}/
